"""CLI が画面に出す文字列と、レポートに書く文言の日本語。

鍵は `i18n.t()` / `i18n.tl()` に渡す**英語の原文そのまま**。原文を直したら、ここの鍵も直すこと
（直し忘れは英語のまま出るだけで落ちない）。tests/test_i18n.py が、コードの中の `t('…')` / `tl(…, '…')` と
この表の過不足・差し込み口の名前を突き合わせる。

埋め込みは `{name}` の名前つき。順番は変えてよいが、**名前は原文と同じもの**を使うこと。
英語の単数・複数（`{n|paper|papers}`）は日本語では使わず、`{n}` と書く。

レポートの文言（見出し・記入欄の名前・確認レベル・採否の名前）は、
既存のレポートを再生成しても文言が変わらないように、ここを変えるときは注意する（記入欄の名前はレポートから読み返す）。
"""

MESSAGES = {
    # -- 採否・深さ・確認レベル（survey.py。CLI の表示とレポートの両方） --------------------
    "Candidate": "候補",
    "Included": "採用",
    "Excluded": "除外",
    "Maybe": "保留",
    "Quick (a narrow topic; get an overview fast)": "簡易（狭いテーマ・短時間で概観をつかむ）",
    "Full (a broad topic; aim for coverage)": "本格（広範なテーマ・網羅性を重視）",
    "unchecked": "未確認",
    "abstract only": "要旨のみ",
    "full text checked": "本文確認済",

    # -- レポートのカード（survey.CARD_FIELDS。レポートから読み返すので変えない） ---------------
    "Evidence": "確認レベル",
    "RQ": "RQ",
    "X (explanatory variable / treatment)": "X（説明変数・介入）",
    "Y (outcome)": "Y（被説明変数・成果）",
    "Data / sample": "データ・サンプル",
    "Identification": "識別戦略",
    "Main findings": "主な結果",
    "Limitations": "限界",
    "Notes": "メモ",
    "Source": "書誌",

    # -- レポートの管理ブロック（survey.py） ----------------------------------------------
    "Research question": "リサーチクエスチョン",
    "Period": "対象期間",
    "Fields": "分野",
    "Inclusion criteria": "採用基準",
    "Exclusion criteria": "除外基準",
    "(not set — set it with `priorwork scope`)": "（未設定 — `priorwork scope` で設定）",
    "Depth": "深さ",
    "Basis of the SSCI status": "SSCI 判定の根拠",
    "checked against the Clarivate list ({file})": "Clarivate 収録リスト照合（{file}）",
    "guessed from the journal name with the built-in list of major journals (verify)": "内蔵の主要誌リストによる誌名推定（要確認）",
    "Paper": "論文",
    "Journal": "掲載誌",
    "X": "X",
    "Y": "Y",
    "Checked": "確認",
    "needs checking": "要確認",
    "(No included papers yet)": "（採用した論文はまだありません）",
    "Unregistered paper (register it with `priorwork add`)": "未登録の論文（`priorwork add` で登録してください）",
    "TL;DR (generated by Semantic Scholar)": "TL;DR（Semantic Scholar 自動生成）",
    "Abstract": "要旨",
    "(no abstract)": "（要旨なし）",
    "no DOI": "DOI なし",
    "cited by {n}": "被引用数 {n}",
    "Counts": "件数",
    "Flow": "流れ",
    "{searches|# search|# searches} and {snowballs|# citation chase|# citation chases} ({hits|# hit|# hits} in all)":
        "検索 {searches} 回・引用をたどる {snowballs} 回（延べ {hits} 件ヒット）",
    "{n|# paper|# papers} after removing duplicates (search {search} / citations {snowball} / added by hand {manual})":
        "重複を除いて {n} 件（検索で見つけた {search} / 引用から {snowball} / 手動登録 {manual}）",
    "included {included}, maybe {maybe}, excluded {excluded}, not screened {candidate}":
        "採用 {included}・保留 {maybe}・除外 {excluded}・未選別 {candidate}",
    "Decisions revised": "採否の見直し",
    "{n} ({numbers}; see the history with `priorwork list`)": "{n} 件（{numbers}。経緯は `priorwork list` で確認）",
    "Reasons for exclusion": "除外理由",
    "{reason} ({n})": "{reason}（{n}）",
    "no reason given": "理由未記入",
    " ({reason})": "（{reason}）",
    ", ": "、",
    " and more": "ほか",
    "Time": "日時",
    "Kind": "種類",
    "Query / target": "クエリ・対象",
    "Conditions": "条件",
    "Hits": "ヒット",
    "New candidates": "新規候補",

    # -- SSCI の判定（ssci.BADGE） -----------------------------------------------------
    "✅ SSCI (checked against the list)": "✅ SSCI収録（リスト照合済）",
    "🟡 Probably SSCI (guessed from the journal name; verify)": "🟡 SSCI収録の可能性大（誌名推定・要確認）",
    "🔍 Journal (SSCI not verified)": "🔍 学術誌（SSCI未確認）",
    "⚪ Not in SSCI (checked against the list)": "⚪ SSCI非収録誌（リスト照合）",
    "📕 Book (outside SSCI)": "📕 書籍（SSCI対象外）",
    "❓ Unknown venue": "❓ 掲載誌不明",
    "❌ Working paper / preprint": "❌ ワーキングペーパー / プレプリント",

    # -- 読むための版（export.py） -----------------------------------------------------
    "(card not filled in)": "（カード未記入）",
    "(not written)": "（未記入）",
    "(not set)": "（未設定）",
    "Draft": "下書き",
    ". ": "。",
    ".": "。",
    "{n|# paper card is|# paper cards are} still \"{unchecked}\" ({numbers})": "確認レベルが「{unchecked}」の論文カード {n} 件（{numbers}）",
    "empty sections: {names}": "未記入の節: {names}",
    "`priorwork check` reports {n|# ERROR|# ERRORs}": "`priorwork check` の ERROR が {n} 件",
    "The format is one of {choices}: {fmt}": "形式は {choices} のいずれかです: {fmt}",
    "Word output needs pandoc (https://pandoc.org/). You can also export HTML and print it to PDF from a browser":
        "Word 形式には pandoc が必要です（https://pandoc.org/）。HTML を書き出してブラウザで印刷（PDF）もできます",

    # -- 状態ファイル（survey.py） -----------------------------------------------------
    "{name} was written by a newer priorwork (format v{version}; this one reads v{supported}). "
    "Update it with `priorwork upgrade`":
        "{name} は新しい版のエンジンで作られています（形式 v{version}、このエンジンは v{supported}）。"
        "`priorwork upgrade` でエンジンを更新してください",
    "The state file": "状態ファイル",
    "depth is one of {choices}: {depth}": "depth は {choices} のどちらかです: {depth}",
    "{name} already exists": "{name} は既に存在します",
    "No survey matches {ref} (see the list with `priorwork status`)": "サーベイが見つかりません: {ref}（`priorwork status` で一覧を確認）",
    "More than one survey matches: {names}": "複数のサーベイが該当します: {names}",
    "The state file is missing: {path}": "状態ファイルがありません: {path}",
    "The report is missing: {path}": "レポートがありません: {path}",
    "#{number} is not in this survey": "#{number} はこのサーベイにありません",
    "(not created yet)": "（まだありません）",
    "A value cannot contain both a quote (') and spaces or #: {value}": "値に ' と空白・# を同時に含めることはできません: {value}",
    "A value must be on one line: {key}": "値は1行で指定してください: {key}",
    "Could not read {file}: {error}": "{file} を読めませんでした: {error}",
    "File not found: {path}": "ファイルが見つかりません: {path}",
    "Give the settings as a JSON object on stdin: {error}": "設定は標準入力に JSON のオブジェクトで渡してください: {error}",
    "Imported the SSCI list: {file} ({n|# journal|# journals})": "SSCI リストを取り込みました: {file}（{n} 誌）",
    "Unknown settings: {names}": "扱えない設定です: {names}",
    "Updated: {names}": "更新しました: {names}",
    "import the SSCI list downloaded from the Master Journal List": "Master Journal List からダウンロードした SSCI リストを取り込む",
    "not set": "未設定",
    "read the values to write as a JSON object from stdin (an empty string removes one)": "書き込む値を標準入力から JSON のオブジェクトで読む（空文字で削除）",
    "set": "設定済み",
    "show or change the settings in .env (API keys, Zotero) and the SSCI list": ".env の設定（API キー・Zotero）と SSCI リストを表示・変更",
    "{file} has no journal title or ISSN column. Download the SSCI list as CSV from the Master Journal List": "{file} に誌名・ISSN の列がありません。Master Journal List から SSCI のリストを CSV でダウンロードしてください",
    "#{number} is not included, so it has no card": "#{number} は採用論文ではないため、カードがありません",
    "Unknown card fields: {names} (use {known})": "カードに無い欄です: {names}（使える欄: {known}）",
    "The evidence level is one of: {keys}": "確認レベルは次のいずれかです: {keys}",
    "Give each field as KEY=VALUE: {item}": "欄は 欄=値 の形で指定してください: {item}",
    "Managed blocks are missing: {names} (restore `<!-- BEGIN priorwork:{first} -->` … `<!-- END priorwork:{first} -->`)":
        "管理ブロックが見つかりません: {names}（`<!-- BEGIN priorwork:{first} -->` 〜 `<!-- END priorwork:{first} -->` を復元してください）",

    # -- 検査（check.py） ------------------------------------------------------------
    "The Markdown does not match the state file. Run `priorwork render`":
        "Markdown が状態ファイルと一致していません。`priorwork render` を実行してください",
    "{label}: the evidence level must be one of {levels}: {value}": "{label}: 確認レベルが不正です（{levels} のいずれか）: {value}",
    "{label}: the evidence level is still \"{unchecked}\"": "{label}: 確認レベルが「{unchecked}」のままです",
    "{label}: some fields are empty ({fields})": "{label}: 未記入の欄があります（{fields}）",
    "{label}: not an SSCI journal ({badge})": "{label}: SSCI 収録誌ではありません（{badge}）",
    "The citation \"{cite}\" in the text has no registered paper "
    "(check that it exists with `priorwork get`, then register it with `priorwork add`)":
        "本文中の引用「{cite}」に対応する論文が登録されていません（`priorwork get` で実在を確認し、`priorwork add` で登録）",
    "The citation \"{cite}\" in the text is {numbers}, which is not included ({statuses})":
        "本文中の引用「{cite}」は {numbers} ですが、採用になっていません（{statuses}）",
    "No included paper is \"{year}\" in the citation \"{cite}\"": "本文中の引用「{cite}」の「{year}」に当たる採用論文がありません",
    " (only one included paper has this author and year, so it needs no a/b)":
        "（同じ著者・年の採用論文は 1 本だけなので a/b は不要です）",
    "The citation \"{cite}\" in the text matches several included papers ({assigned}). "
    "Tell them apart as {year}a / {year}b, as the references do":
        "本文中の引用「{cite}」は採用論文の複数に当たります（{assigned}）。参照文献に合わせて {year}a / {year}b のように区別してください",
    "Not checked, taken for an organisation or a table/figure number: {cites} "
    "(if one is a paper, register it with `priorwork add`)":
        "組織名・図表番号とみなして照合しなかった引用: {cites}（論文なら `priorwork add` で登録）",
    "The DOI {doi} in the text is not registered": "本文中の DOI {doi} が登録されていません",
    "{label}: OpenAlex does not know the DOI {doi}": "{label}: DOI {doi} が OpenAlex に見つかりません",
    "{label}: the DOI points to another title: \"{title}\"": "{label}: DOI が別タイトルを指しています: \"{title}\"",
    "{n|# candidate is|# candidates are} not screened yet (`priorwork list {name} --status candidate maybe`)":
        "未選別の候補が {n} 件あります（`priorwork list {name} --status candidate maybe`）",
    "No paper is included yet": "採用した論文がまだありません",
    "The depth is full, but the citations have not been chased (`priorwork snowball {name}`). "
    "If quick is enough, change it with `priorwork scope {name} --depth quick`":
        "深さが full ですが、引用をたどっていません（`priorwork snowball {name}`）。"
        "quick で足りるなら `priorwork scope {name} --depth quick` に変えてください",
    "The depth is full, but {n|# card is|# cards are} \"{abstract}\" (take the core papers to the full text: {numbers})":
        "深さが full ですが、{n} 件が「{abstract}」です（中核論文は本文確認まで進める: {numbers}）",

    # -- 文献 API（api.py） -----------------------------------------------------------
    "an HTML error page": "HTML のエラーページ",
    "May be a book review or comment (guessed from the title or the page range)": "書評・コメントの可能性（タイトルの形式またはページ数から推定）",
    "rate limited (HTTP 429)": "レート制限 (HTTP 429)",
    "{reason}. Retrying in {seconds} s ({attempt}/{max})": "{reason}。{seconds}秒待って再試行します ({attempt}/{max})",
    "gave up after {n|# retry|# retries} ({detail})": "{n} 回再試行しても成功しませんでした（{detail}）",
    "network error: {error}": "ネットワークエラー: {error}",
    "the publisher does not make the {kind} public": "{kind} は出版社により非公開",
    "OpenAlex can only look up a DOI or an OpenAlex ID: {id}": "DOI / OpenAlex ID 以外は OpenAlex で引けません: {id}",
    "No DOI": "DOI なし",
    "{error} → the DOIs are not checked with OpenAlex (the details from S2 are kept)":
        "{error} → OpenAlex での DOI 照合をスキップします（S2 の書誌情報のまま）",
    "DOI not verified": "DOI 未照合",
    "OpenAlex does not know the DOI (verify the DOI)": "OpenAlex に DOI が見つからない（DOI 要確認）",
    "The DOI points to another title: \"{title}\" (verify the DOI)": "DOI が別タイトルを指している: \"{title}\"（DOI 要確認）",
    "S2 gives the journal as \"{journal}\", but the DOI is a working paper / preprint version "
    "(find the DOI of the published version)":
        "S2 上の掲載誌は「{journal}」だが DOI は WP / プレプリント版（掲載版の DOI を確認）",
    "There is no DOI, so OpenAlex cannot look it up: {id}": "DOI が無いため OpenAlex で照合できません: {id}",
    "Not in Semantic Scholar; fetching it from OpenAlex: {id}": "Semantic Scholar に見つからないため OpenAlex で取得します: {id}",
    "{id} is in neither Semantic Scholar nor OpenAlex (perhaps a domestic journal, a very recent paper or a wrong DOI)":
        "{id} は Semantic Scholar にも OpenAlex にも見つかりません（国内誌・ごく最近の論文・DOI の誤りなどの可能性）",
    "{error}: {id} → fetching it from OpenAlex (by citations)": "{error}: {id} → OpenAlex で取得します（被引用数順）",

    # -- 本文の取得（fulltext.py） ------------------------------------------------------
    "Could not download the PDF (HTTP {status}): {url}": "PDF をダウンロードできません（HTTP {status}）: {url}",
    "The PDF is too large (>{mb} MB): {url}": "PDF が大きすぎます（>{mb}MB）: {url}",
    "Not a PDF (probably the publisher's landing page): {url}": "PDF ではありません（出版社のランディングページの可能性）: {url}",
    "No such file: {path}": "ファイルがありません: {path}",
    "No PDF in the local Zotero ({path})": "ローカルの Zotero（{path}）に PDF なし",
    "Not in the Zotero library (matched by DOI and title)": "Zotero ライブラリに未登録（DOI・タイトルで照合）",
    "In Zotero, but no PDF is attached": "Zotero に登録済みだが PDF の添付なし",
    "Zotero has no indexed full text": "Zotero の索引済み本文テキストなし",
    "No open-access PDF": "オープンアクセス版の PDF なし",
    "No full-text PDF was found:": "本文 PDF が見つかりません:",
    "Attach the PDF in Zotero, or give it with `--pdf <path>`": "Zotero で PDF を添付するか、`--pdf <パス>` で指定してください",
    "Could not extract text from the PDF (probably a scanned image): {source}":
        "PDF からテキストを抽出できませんでした（スキャン画像の PDF の可能性）: {source}",

    # -- Zotero（zotero.py） ----------------------------------------------------------
    "Cannot connect: {error}": "接続できません: {error}",
    "HTTP {status}. Retrying in {seconds} s": "HTTP {status}。{seconds}秒待って再試行します",
    "Authentication failed (HTTP {status}). Check the key, user ID and password in .env, "
    "and the key's permissions (library access)":
        "認証に失敗しました（HTTP {status}）。.env のキー・ユーザー ID・パスワードと、キーの権限（library access）を確認してください",
    "Gave up after too many retries": "再試行の上限に達しました",
    "Cannot read the library (HTTP {status}): {detail}": "ライブラリを取得できません（HTTP {status}）: {detail}",
    "A linked file ({name}) is not synced to the server, so it cannot be fetched":
        "リンクされたファイル（{name}）はサーバーに同期されないため取得できません",
    "{file} is not on the WebDAV server (Zotero may not have synced the file yet)":
        "WebDAV に {file} がありません（Zotero でファイルが未同期の可能性）",
    "Cannot fetch from WebDAV (HTTP {status}): {url}": "WebDAV から取得できません（HTTP {status}）: {url}",
    "The file is not in Zotero File Storage (if you sync with WebDAV, set ZOTERO_WEBDAV_URL)":
        "Zotero File Storage にファイルがありません（WebDAV 同期の場合は ZOTERO_WEBDAV_URL を設定）",
    "Cannot fetch from Zotero File Storage (HTTP {status})": "Zotero File Storage から取得できません（HTTP {status}）",
    "The file fetched is not a PDF": "取得したファイルが PDF ではありません",
    "Cannot fetch the full text (HTTP {status})": "本文テキストを取得できません（HTTP {status}）",
    "not set (Zotero File Storage is used)": "未設定（Zotero File Storage を使う）",
    "connected": "接続できました",
    "authentication failed (HTTP {status})": "認証に失敗しました（HTTP {status}）",
    "folder not found (check that ZOTERO_WEBDAV_URL ends in .../zotero/)":
        "フォルダが見つかりません（ZOTERO_WEBDAV_URL の末尾が .../zotero/ になっているか確認）",
    "unexpected response (HTTP {status})": "想定外の応答（HTTP {status}）",
    "The file on the WebDAV server is not a readable ZIP": "WebDAV のファイルが ZIP として読めません",
    "There is no PDF in the ZIP": "ZIP の中に PDF がありません",
    "The PDF is too large ({mb} MB)": "PDF が大きすぎます（{mb}MB）",
    "The file in the ZIP is not a PDF": "ZIP の中のファイルが PDF ではありません",

    # -- ワークスペース（scaffold.py） ---------------------------------------------------
    "AGENTS.md and the skills do not match the engine's version. Update them with `./priorwork sync`":
        "AGENTS.md・スキルがエンジンの版と一致しません。`./priorwork sync` で更新してください",
    "Some files were changed by hand ({files}); `./priorwork sync` leaves them alone. "
    "Move your own instructions to AGENTS.local.md and restore them with `./priorwork sync --force`":
        "手元で変更されているファイルがあります（{files}）。`./priorwork sync` は上書きしません。"
        "独自の指示は AGENTS.local.md に移し、`./priorwork sync --force` で元に戻してください",
    "This is the engine's own repository. Run it in a workspace directory":
        "ここはエンジン自身のリポジトリです。ワークスペースのディレクトリで実行してください",
    "Could not look up the latest version on PyPI: {error}": "PyPI で最新の版を確認できませんでした: {error}",
    "Give the version as X.Y.Z: {version}": "版は X.Y.Z の形で指定してください: {version}",
    "pip install failed (requirements.txt was restored): {error}":
        "pip install に失敗しました（requirements.txt は元に戻しました）: {error}",

    # -- 診断（doctor.py） ------------------------------------------------------------
    "Layout": "構成",
    "Missing directories: {dirs} (create them with `priorwork init`)": "ディレクトリがありません: {dirs}（`priorwork init` で作成）",
    "reports/ and .priorwork/ are there ({root})": "reports/ と .priorwork/ があります（{root}）",
    "Workspace language": "ワークスペースの言語",
    "{lang} (reports, AGENTS.md and the skills)": "{lang}（レポート・AGENTS.md・スキル）",
    "Display language": "表示の言語",
    "{lang} (PRIORWORK_LANG, or the locale)": "{lang}（PRIORWORK_LANG、無ければロケール）",
    "AGENTS.md and skills": "AGENTS.md・スキル",
    "They match the engine's version": "エンジンの版と一致しています",
    "Engine version": "エンジンの版",
    "requirements.txt says {pinned}, but {installed} is installed (`./priorwork upgrade` or `pip install -r requirements.txt`)":
        "requirements.txt は {pinned} ですが、インストール済みは {installed} です（`./priorwork upgrade` か `pip install -r requirements.txt`）",
    " (requirements.txt: {pinned})": "（requirements.txt: {pinned}）",
    "Not a Git repository. Run `git init`, then create a private repository on GitHub and push":
        "Git のリポジトリではありません。`git init` し、GitHub に非公開リポジトリを作って push してください",
    ".env in Git": ".env の管理",
    ".env is committed to Git. Remove it with `git rm --cached .env` and issue new API keys":
        ".env が Git に登録されています。`git rm --cached .env` で外し、API キーを再発行してください",
    ".env is not in .gitignore. Fix .gitignore with `./priorwork sync`":
        ".env が .gitignore に入っていません。`./priorwork sync` で .gitignore を直してください",
    "No remote. Publish it as a private repository on GitHub (VS Code: the sidebar's Publish to GitHub; or `gh repo create <name> --private --source=. --push`)":
        "リモートがありません。GitHub に非公開リポジトリとして公開してください（VS Code ではサイドバーの「GitHub に公開」、または `gh repo create <名前> --private --source=. --push`）",
    "The remote is not GitHub: {urls}": "リモートが GitHub ではありません: {urls}",
    "Remote: {urls}": "リモート: {urls}",
    "There is no .env. Set your API keys in the settings (VS Code: Priorwork's Settings; command line: `priorwork settings`)":
        ".env がありません。設定で API キーを入れてください（VS Code では Priorwork の設定、コマンドラインでは `priorwork settings`）",
    "An API key is set": "API キーが設定されています",
    "No API key. Requests share a public pool, so searches often fail with HTTP 429":
        "API キー未設定。共有枠のため HTTP 429 で検索が失敗しやすくなります",
    "Set": "設定されています",
    "No key or e-mail (it works, with a daily usage cap)": "キー・メール未設定（使えますが、1 日の利用量に上限があります）",
    "SSCI journal list": "SSCI 収録リスト",
    "{file} ({n|# ISSN|# ISSNs})": "{file}（{n} 件の ISSN）",
    "Not set, so the SSCI status is guessed from the journal name (🟡). Import Clarivate's CSV in the settings (`priorwork settings --import-ssci CSV`)":
        "未設定。誌名による推定（🟡）になります。設定で Clarivate の CSV を取り込んでください（`priorwork settings --import-ssci CSV`）",
    "Not set (optional; with it, priorwork can see what is in Zotero and fetch full texts)":
        "未設定（任意。設定すると登録状況の確認と本文取得ができます）",
    "Found (`priorwork export --format docx` works)": "あります（`priorwork export --format docx` が使えます）",
    "Not found (optional; needed only for Word output, not for HTML)": "なし（任意。Word 形式で書き出すときだけ必要。HTML は不要）",
    "Semantic Scholar connection": "Semantic Scholar 接続",
    "OpenAlex connection": "OpenAlex 接続",
    "Responded": "応答しました",
    "Responded, but with no results": "応答しましたが、結果が空でした",
    "Zotero connection": "Zotero 接続",
    "WebDAV: {status}": "WebDAV: {status}",

    # -- CLI（cli.py） ---------------------------------------------------------------
    "Abstract: {text}": "要旨: {text}",
    "No SSCI journal list is set, so the SSCI status is guessed from the journal name.":
        "SSCI 収録リストが未設定のため、SSCI 判定は誌名による推定です。",
    "new candidate": "新規候補",
    "already registered: {status}": "登録済: {status}",
    "updated: {path}": "更新: {path}",
    "removed: {path}": "削除: {path}",
    "skipped (not written by priorwork): {path}  → to overwrite it, `priorwork sync --force`":
        "スキップ（由来の分からないファイル）: {path}  → 上書きするなら `priorwork sync --force`",
    "skipped (changed by hand): {path}  → see the diff with `priorwork sync --diff`, overwrite with `--force`":
        "スキップ（手元で変更されている）: {path}  → 差分は `priorwork sync --diff`、上書きするなら `--force`",
    "no changes": "変更なし",
    "No differences": "差分はありません",
    "Workspace: {root} (priorwork {version}, {lang})": "ワークスペース: {root}（priorwork {version}、{lang}）",
    "Next: copy `.env.example` to `.env`, set your API keys and check with `./priorwork doctor`.\n"
    "    Make the first commit and push it to a private GitHub repository "
    "(e.g. `gh repo create <name> --private --source=. --push`).\n"
    "    Then start a survey with `./priorwork new \"<topic>\" --slug <slug>`":
        "次: `cp .env.example .env` で API キーを設定し、`./priorwork doctor` で確認します。\n"
        "    最初のコミットをして GitHub の非公開リポジトリに push します（例: `gh repo create <名前> --private --source=. --push`）。\n"
        "    その後、`./priorwork new \"<テーマ>\" --slug <slug>` でサーベイを始めます",
    "{ng|# problem|# problems} / {warn|# warning|# warnings}": "問題 {ng} / 注意 {warn}",
    " (check the connections with `priorwork doctor --online`)": "（接続の確認は `priorwork doctor --online`）",
    "Updated the engine to {version}. Review the changes with `git diff requirements.txt AGENTS.md .agent` and commit them.":
        "エンジンを {version} に更新しました。`git diff requirements.txt AGENTS.md .agent` で変更を確認してコミットします。",
    "Set the scope": "調査範囲を決める",
    "Search": "検索する",
    "Screen {n|# candidate|# candidates}": "候補 {n} 件を選別する",
    "Chase citations to find what was missed": "引用をたどって見落としを補う",
    "(Optional) chase citations if you worry about missed papers": "（任意）見落としが気になれば引用をたどる",
    "Add {n|# included paper|# included papers} to Zotero ({numbers})": "採用論文のうち Zotero 未登録 {n} 件（{numbers}）を Zotero に登録する",
    "Fill in {n|# card|# cards} from the abstracts ({numbers}); \"abstract only\" is fine":
        "カード未記入の採用論文 {n} 件（{numbers}）を要旨から埋める（確認レベルは「要旨のみ」でよい）",
    "Fill in {n|# card|# cards} from the full texts ({numbers})": "カード未記入の採用論文 {n} 件（{numbers}）を本文を取得して埋める",
    "Check": "検査する",
    "Write the version for reading (HTML)": "読むための版（HTML）を書き出す",
    "No surveys yet. Create one with `priorwork new \"<topic>\" --slug <english_slug>`.":
        "サーベイはまだありません。`priorwork new \"<テーマ>\" --slug <english_slug>` で作成します。",
    "included {included} / maybe {maybe} / candidates {candidate} / excluded {excluded}":
        "採用 {included} / 保留 {maybe} / 候補 {candidate} / 除外 {excluded}",
    "Report: {path}": "レポート: {path}",
    "RQ: {question} | period: {years} | depth: {depth}": "RQ: {question} | 期間: {years} | 深さ: {depth}",
    "{n|# search|# searches}": "検索 {n} 回",
    "Next:": "次にやること:",
    "Created: {path}": "作成しました: {path}",
    "Next: priorwork search \"<English query>\" --into {name}": "次: priorwork search \"<英語クエリ>\" --into {name}",
    "{name}: {n|# paper|# papers} ({statuses})": "{name}: {n} 件（{statuses}）",
    "found by: {how}": "発見: {how}",
    "full text fetched": "本文取得済",
    "history: {trail}": "経緯: {trail}",
    "Error: {message}": "Error: {message}",
    "An exclusion needs a reason (--reason \"...\")": "除外には理由が必要です（--reason \"...\"）",
    "new": "新規",
    "already registered": "登録済",
    "updated": "更新しました",
    "{n|# included paper is|# included papers are} not in Zotero: {numbers} (`priorwork zotero {name}`)":
        "Zotero 未登録の採用論文 {n} 件: {numbers}（`priorwork zotero {name}`）",
    " — no problems": " — 問題なし",
    "Written: {path}": "書き出しました: {path}",
    "Written as a draft (marked at the top):": "下書きとして書き出しました（冒頭に表示があります）:",
    "Full text: {path} ({pages} pages, {chars} characters)": "本文テキスト: {path}（{pages} ページ, {chars} 文字）",
    "Source: {source}": "取得元: {source}",
    "* This is Zotero's index text, which has no page breaks. Check the PDF before giving page numbers.":
        "※ Zotero の索引テキストのためページ区切りがありません。ページ番号を書くときは PDF で確認してください。",
    "* Extracted text can garble columns, tables and formulas. Check numbers against the page in the PDF too.":
        "※ 抽出テキストは段組み・表・数式が崩れていることがあります。数値は PDF の該当ページでも確認してください。",
    "Zotero is not set up. Set ZOTERO_API_KEY and ZOTERO_USER_ID in .env":
        "Zotero 連携が未設定です。.env に ZOTERO_API_KEY と ZOTERO_USER_ID を設定してください",
    "Zotero library: {n|# item|# items} ({doi} with a DOI) / {pdfs|# PDF attached|# PDFs attached} | "
    "library version {version} | synced {synced}":
        "Zotero ライブラリ: 論文等 {n} 件（DOI あり {doi} 件）/ PDF 添付 {pdfs} 件 | ライブラリ版 {version} | 同期 {synced}",
    "{name}: Zotero status of {n|# paper|# papers} ({statuses})": "{name}: {n} 件の Zotero 登録状況（{statuses}）",
    "in Zotero ({n|# PDF|# PDFs})": "登録済（PDF {n}）",
    "in Zotero (no PDF)": "登録済（PDF なし）",
    "not in Zotero": "未登録",
    "{n|# paper is|# papers are} not in Zotero": "未登録 {n} 件",
    " (add them to Zotero by hand; this command picks them up the next time it runs)":
        "（Zotero に手作業で登録してください。登録後の同期はこのコマンドで自動反映）",
    "Results for '{query}': {n|# paper|# papers}": "'{query}' の検索結果: {n} 件",
    "'{query}' → {n|# paper|# papers} ({new} new {new|candidate|candidates} added to {name})":
        "'{query}' → {n} 件（新規候補 {new} 件を {name} に登録）",
    "No paper is included yet. Include some with `priorwork include` first":
        "採用した論文がありません。先に `priorwork include` で採用してください",
    "citations of {n|# included paper|# included papers} ({direction})": "採用 {n} 本の引用関係（{direction}）",
    "Unregistered papers linked by citations to {seeds|# included paper|# included papers}: {linked} → "
    "registered the top {n} with at least {threshold|# link|# links} as candidates":
        "採用 {seeds} 本と引用関係にある未登録の論文: {linked} 本 → リンク数 {threshold} 以上の上位 {n} 件を候補に登録",
    "({n|# included paper was|# included papers were} skipped: no DOI or OpenAlex ID, or not found in OpenAlex)":
        "（DOI / OpenAlex ID が無い、または OpenAlex で見つからない採用論文 {n} 本は対象外）",
    "{total|# link|# links} (cited by the included papers {references} / citing them {citations})":
        "リンク数 {total}（採用論文が参照 {references} / 採用論文を引用 {citations}）",
    " (DOI verified with OpenAlex)": " (OpenAlex で DOI 照合済)",
    "by citations": "被引用数順",
    "in S2's order (roughly newest first)": "S2 の返却順（概ね新しい順）",
    "Papers citing {id}: {n} ({order})": "{id} を引用している論文: {n} 件（{order}）",
    "References of {id}: {n} ({order})": "{id} の参考文献: {n} 件（{order}）",
    "Basis: {basis}": "判定根拠: {basis}",

    # -- --help（cli.py の USAGE_LINES と argparse の help） ---------------------------------
    "priorwork — build literature reviews for the social sciences, in conversation with an AI agent":
        "priorwork — AI エージェントと対話しながら、社会科学の先行研究サーベイを作る",
    "Workspace": "ワークスペースの管理",
    "  init [DIR]                 set up a workspace (reports/, .priorwork/, AGENTS.md, skills, …)":
        "  init [DIR]                 ワークスペースを初期化（reports/ .priorwork/ AGENTS.md スキルなど）",
    "  sync [--force|--diff]      update AGENTS.md, the skills and ./priorwork to the engine's version":
        "  sync [--force|--diff]      AGENTS.md・スキル・./priorwork をエンジンの版に更新（手元の変更は上書きしない）",
    "  doctor [--online]          diagnose the setup (API keys, SSCI list, engine version, …)":
        "  doctor [--online]          設定（API キー・SSCI リスト・エンジンの版など）を診断",
    "  upgrade [--to X.Y.Z]       update the engine to the latest (or given) version, then sync":
        "  upgrade [--to X.Y.Z]       エンジンを最新（または指定）の版に更新して sync",
    "Surveys": "サーベイの管理",
    "  status [SURVEY]            list the surveys / progress and next steps":
        "  status [SURVEY]            サーベイ一覧 / 進捗と次にやること",
    "  new TOPIC --slug SLUG      create a survey (reports/YYYYMMDD_<slug>.md and .priorwork/surveys/*.json)":
        "  new TOPIC --slug SLUG      サーベイを作成（reports/YYYYMMDD_<slug>.md と .priorwork/surveys/*.json）",
    "  scope SURVEY ...           set the scope (research question, period, criteria)":
        "  scope SURVEY ...           調査範囲（RQ・期間・採否基準）を設定",
    "  list SURVEY                list the papers (numbers, decisions, SSCI)":
        "  list SURVEY                論文の一覧（番号・採否・SSCI）",
    "  include / exclude / maybe  record decisions (e.g. priorwork include SURVEY 2 5 7)":
        "  include / exclude / maybe  採否を記録（例: priorwork include SURVEY 2 5 7）",
    "  add SURVEY DOI...          register papers by DOI (included by default)":
        "  add SURVEY DOI...          DOI を指定して登録（既定で採用）",
    "  card SURVEY N [--set ...]  show or fill in the card of an included paper":
        "  card SURVEY N [--set ...]  採用論文のカードを表示・記入",
    "  settings                   show or change the API keys, Zotero and the SSCI list":
        "  settings                   API キー・Zotero・SSCI リストの設定を表示・変更",
    "  render SURVEY              regenerate the managed blocks of the Markdown":
        "  render SURVEY              Markdown の管理ブロックを再生成",
    "  export SURVEY              write the report for reading (HTML / Word / Markdown)":
        "  export SURVEY              読むためのレポートを書き出す（HTML / Word / Markdown）",
    "  check SURVEY               find empty fields, unregistered citations and DOI mismatches":
        "  check SURVEY               記入漏れ・未登録の引用・DOI の不整合を検査",
    "  fulltext SURVEY N          get the full text (Zotero / open-access PDF)":
        "  fulltext SURVEY N          本文テキストを取得（Zotero / OA PDF）",
    "  zotero [SURVEY]            check the Zotero link / which included papers are in Zotero":
        "  zotero [SURVEY]            Zotero 連携の確認 / 採用論文の Zotero 登録状況",
    "Finding literature": "文献の探索",
    "  search QUERY [--into SURVEY]   search (--into registers the results as candidates)":
        "  search QUERY [--into SURVEY]   検索（--into で候補として登録）",
    "  snowball SURVEY                register candidates from the citations of the included papers":
        "  snowball SURVEY                採用論文の引用関係から候補を登録",
    "  get / citations / references   paper details and citation links":
        "  get / citations / references   論文詳細・引用関係",
    "  journal NAME_OR_ISSN           the SSCI status of a journal":
        "  journal NAME_OR_ISSN           雑誌の SSCI 判定",
    "do not use the cache of API responses": "API レスポンスのキャッシュを使わない",
    "print JSON (for the VS Code extension and scripts)": "JSON で出力する（VS Code の拡張機能・スクリプト向け）",
    "number of papers (default: 10)": "件数 (default: 10)",
    "only papers in SSCI journals (including guessed ones)": "SSCI 収録（推定含む）誌の論文だけにする",
    "also include working papers, preprints, books and unknown venues": "WP・プレプリント・書籍・掲載誌不明も含める",
    "show the start of the abstract when there is no TL;DR": "TL;DR が無い論文は要旨の冒頭を表示",
    "set up a workspace": "ワークスペースを初期化",
    "the directory (default: the current workspace)": "初期化するディレクトリ（既定: 現在のワークスペース）",
    "the language of the reports, AGENTS.md and the skills (default: the display language)":
        "レポート・AGENTS.md・スキルの言語（既定: 表示の言語）",
    "update AGENTS.md, the skills and ./priorwork to the engine's version": "AGENTS.md・スキル・./priorwork をエンジンの版に更新",
    "also overwrite files changed by hand": "独自に変更されたファイルも上書きする",
    "show the differences from the engine's version without writing": "書き換えずに、エンジンの版との差分を表示する",
    "diagnose the setup": "設定を診断",
    "also check the connections to Semantic Scholar, OpenAlex and Zotero": "Semantic Scholar・OpenAlex・Zotero への接続も確認する",
    "update the engine, then sync": "エンジンを更新して sync",
    "the version to update to (default: the latest)": "更新先の版（既定: 最新）",
    "list the surveys / progress and next steps": "サーベイ一覧 / 進捗と次にやること",
    "the research question": "リサーチクエスチョン",
    "the period (e.g. 2000-2024)": "対象期間（例: 2000-2024）",
    "the fields (e.g. labour economics, sociology)": "分野（例: 労働経済学, 社会学）",
    "inclusion criteria": "採用基準",
    "exclusion criteria": "除外基準",
    "the depth of the survey (quick or full; default full)": "サーベイの深さ（quick: 簡易 / full: 本格。既定 full）",
    "create a survey": "サーベイを作成",
    "the topic (any language)": "テーマ（日本語可）",
    "an English slug for the file name (e.g. minimum_wage_employment)": "ファイル名用の英語スラッグ（例: minimum_wage_employment）",
    "the language of the report (default: the workspace's)": "レポートの言語（既定: ワークスペースの言語）",
    "set the scope": "調査範囲を設定",
    "list the papers": "論文の一覧",
    "filter (one or more)": "絞り込み（複数可）",
    "also show the start of the abstract": "要旨の冒頭も表示",
    "include": "採用",
    "exclude (--reason is required)": "除外（--reason 必須）",
    "maybe": "保留",
    "back to candidate": "候補に戻す",
    "paper numbers (without #)": "論文番号（#なし）",
    "the reason": "理由",
    "register papers by DOI or ID (included by default)": "DOI / ID を指定して登録（既定で採用）",
    "register as a candidate, not as included": "採用ではなく候補として登録",
    "show or fill in the card of an included paper": "採用論文のカードを表示・記入",
    "fields to write (evidence=unchecked|abstract|fulltext, rq, x, y, data, method, findings, limits, memo); "
    "a new line starts the bullet points below":
        "書き込む欄（evidence=unchecked|abstract|fulltext、rq、x、y、data、method、findings、limits、memo）。"
        "改行の後ろは直下の箇条書きになる",
    "regenerate the managed blocks of the Markdown": "Markdown の管理ブロックを再生成",
    "check the survey": "サーベイを検査",
    "do not re-check the DOIs with OpenAlex": "OpenAlex での DOI 再確認をしない",
    "write the report for reading": "読むためのレポートを書き出す",
    "the format (default: html)": "出力形式（既定: html）",
    "where to write it (default: next to the report in reports/)": "出力先（既定: reports/ 内、レポートと同じ名前）",
    "also include each paper's abstract": "各論文の要旨も載せる",
    "get the full text": "本文テキストを取得",
    "the paper number": "論文番号",
    "the path of the PDF": "PDF のパスを直接指定",
    "check the Zotero link / which included papers are in Zotero": "Zotero 連携の確認 / 採用論文の Zotero 登録状況",
    "which papers (default: included only)": "対象（既定: 採用のみ）",
    "reload the whole library instead of the changes": "差分ではなくライブラリ全体を取り直す",
    "search": "検索",
    "an English query (--bulk accepts + | - \"...\")": "英語の検索クエリ（--bulk では + | - \"...\" が使える）",
    "register the results as candidates of the survey": "結果を候補としてサーベイに登録",
    "a year or a range (e.g. 2015-2024)": "出版年または範囲（例: 2015-2024）",
    "bulk search (boolean operators, most cited first)": "bulk 検索（ブール演算・被引用数の多い順に取得）",
    "citations / relevance / recent (newest first) / cpy (citations per year)":
        "citations: 被引用数 / relevance: 関連度 / recent: 新しい順 / cpy: 年あたり被引用数",
    "register candidates from the citations of the included papers": "採用論文の引用関係から候補を登録",
    "citing papers to look at per included paper (default: 50)": "採用論文 1 本あたりに見る被引用論文数 (default: 50)",
    "minimum number of links (default: 2 with three or more included papers, else 1)":
        "最低リンク数（既定: 採用 3 本以上なら 2、未満なら 1）",
    "paper details": "論文詳細",
    "papers citing this paper": "この論文を引用している論文",
    "the references of this paper": "この論文の参考文献",
    "recent: S2's order (roughly newest first) / cited: by citations (OpenAlex)":
        "recent: S2 の返却順（概ね新しい順）/ cited: 被引用数順 (OpenAlex)",
    "the SSCI status of a journal name or ISSN": "誌名 / ISSN の SSCI 判定",
    # 検索の件数・Zotero のコレクション
    "number of papers (default: 25 for a full survey, else 10)": "件数（既定: full のサーベイは 25、それ以外は 10）",
    "No hits. Bulk search takes + (AND), | (OR), - (NOT) and \"phrases\"; try fewer terms or synonyms":
        "0 件でした。bulk 検索では + (AND)・| (OR)・- (NOT)・\"フレーズ\" を使います。語を減らすか、同義語で試してください",
    "No hits. Try fewer terms, synonyms or --bulk": "0 件でした。語を減らすか、同義語か --bulk で試してください",
    "Search more: a full survey usually needs {min_q}+ queries and {min_n}+ papers "
    "(now {queries|# query|# queries}, {n|# paper|# papers})":
        "検索を足す: full のサーベイでは、{min_q} クエリ・{min_n} 本以上が目安（いまは {queries} クエリ・{n} 本）",
    "Register {n|# paper|# papers} from the Zotero collection \"{name}\" as candidates":
        "Zotero のコレクション「{name}」の {n} 本を候補に登録する",
    "  zotero SURVEY --collection NAME   link a Zotero collection (--import registers its papers, --dois lists the DOIs to add)":
        "  zotero SURVEY --collection 名前   Zotero のコレクションを結び付ける（--import で中の論文を登録、--dois で追加する DOI の一覧）",
    "Cannot read the collections (HTTP {status})": "コレクションを読めません（HTTP {status}）",
    "No Zotero collection named \"{name}\". The collections: {names}":
        "「{name}」という Zotero のコレクションはありません。コレクション: {names}",
    "More than one Zotero collection is named \"{name}\"; give the path or the key: {names}":
        "「{name}」という Zotero のコレクションが複数あります。パスかキーで指定してください: {names}",
    "(none)": "（なし）",
    "No collections in the Zotero library": "Zotero のライブラリにコレクションはありません",
    "{n|# item|# items}": "{n} 件",
    "Linked the Zotero collection \"{name}\" to {survey}": "Zotero のコレクション「{name}」を {survey} に結び付けました",
    "Unlinked the Zotero collection from {survey}": "{survey} と Zotero のコレクションの結び付きを外しました",
    "No Zotero collection is linked to {survey}. Link one with "
    "`priorwork zotero {survey} --collection \"<name>\"`":
        "{survey} に Zotero のコレクションが結び付いていません。"
        "`priorwork zotero {survey} --collection \"<名前>\"` で結び付けてください",
    "Imported from the Zotero collection: {n|# paper|# papers} ({new} new)":
        "Zotero のコレクションから取り込みました: {n} 本（新規 {new}）",
    "not imported (no DOI, or not found): {title}": "取り込めなかったもの（DOI が無い / 見つからない）: {title}",
    "collection: {name}": "コレクション: {name}",
    "in Zotero, not in the collection": "Zotero にあるがコレクションに無い",
    "To add them at once: copy the DOIs from `priorwork zotero {name} --dois` and paste them into Zotero's "
    "\"Add Item by Identifier\" (the magic wand){where}":
        "まとめて足すには: `priorwork zotero {name} --dois` の DOI をコピーし、{where}Zotero の"
        "「識別子でアイテムを追加」（魔法の杖）に貼ります",
    " with the collection \"{name}\" selected": "コレクション「{name}」を選んだ状態で",
    "{n|# paper is|# papers are} in the collection but not in the survey yet: "
    "`priorwork zotero {name} --import` registers them as candidates":
        "コレクションにあってサーベイにまだ無い論文が {n} 本あります: "
        "`priorwork zotero {name} --import` で候補に登録します",
    "list the collections of the Zotero library": "Zotero のライブラリのコレクションを一覧する",
    "link a Zotero collection (name, path or key) to the survey; \"\" unlinks it":
        "Zotero のコレクション（名前・パス・キー）をサーベイに結び付ける（\"\" で外す）",
    "register the papers of the linked collection as candidates": "結び付けたコレクションの論文を候補に登録する",
    "print only the DOIs of the papers not in Zotero (for the magic wand)":
        "Zotero に無い論文の DOI だけを出す（魔法の杖に貼る用）",
}
