"""ワークスペースの初期化・エンジン由来ファイルの同期・更新・旧構成からの移行。

エンジン（priorwork パッケージ）は AGENTS.md・スキル・`./priorwork` ラッパーを同梱している（言語ごとに
`assets/<lang>/`）。`priorwork sync` はワークスペースの言語のものを書き出し、エンジンを更新したときに最新へ揃える。
書き出したファイルは `.priorwork/sync.json` に記録し、記録にないファイルを黙って上書きしない。

旧構成からの移行（`priorwork migrate`）は2種類:
  - 旧名 lit のワークスペース（`.lit/`、`./lit`、`litsurvey @ git+…/lit.git`）
  - さらに古い構成（`surveys/` に md と json が同居、`data/*.csv`）
"""

import difflib
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from . import __version__, i18n
from .i18n import t
from .survey import Survey, SurveyError
from .workspace import (
    ASSETS_DIR, ENGINE_DIR, LEGACY_META, assets_dir, cache_dir, config_path, data_dir, load_config, meta_dir,
    reports_dir, save_config, state_dir, workspace_lang,
)

DIST = "priorwork"                                   # PyPI の配布名
PYPI_JSON = f"https://pypi.org/pypi/{DIST}/json"
MANIFEST = "sync.json"
SKILLS_LINK = ".claude/skills"
WRAPPER_NAME = "priorwork"

WRAPPER = """#!/bin/sh
# Run `./priorwork <command>` from the workspace (written by `priorwork sync`; uses .venv when there is one)
ROOT="$(cd "$(dirname "$0")" && pwd)"
PY="$ROOT/.venv/bin/python"
[ -x "$PY" ] || PY=python3
PRIORWORK_WORKSPACE="${PRIORWORK_WORKSPACE:-$ROOT}" exec "$PY" -m priorwork "$@"
"""

LOCAL_INSTRUCTIONS = {
    "ja": """# このワークスペース固有のエージェント向け指示

AGENTS.md は `priorwork sync` が生成するため、直接編集しないでください。
このワークスペース独自の指示（優先する分野・文体・除外したい誌名など）はここに書きます。
""",
    "en": """# Instructions for agents specific to this workspace

AGENTS.md is generated by `priorwork sync`; do not edit it.
Write instructions for this workspace only (fields to prefer, writing style, journals to leave out, …) here.
""",
}

GITIGNORE_BEGIN = "# BEGIN priorwork (managed by `priorwork sync`)"
GITIGNORE_END = "# END priorwork"
GITIGNORE_LINES = [".env", ".venv/", "__pycache__/", ".priorwork/cache/", ".priorwork/data/",
                   "reports/*.html", "reports/*.docx", "reports/*.clean.md"]  # priorwork export の出力（再生成できる）
# 旧名 lit が管理していたブロック（移行のときに消す）
LEGACY_GITIGNORE_BLOCKS = (("# BEGIN lit (managed by `lit sync`)", "# END lit"),)
# さらに古い構成の除外設定。`.lit/` 全体を除外すると状態ファイルが Git に載らない
LEGACY_GITIGNORE_LINES = {".lit/", ".priorwork/", "data/*.csv"}


class ScaffoldError(Exception):
    pass


@dataclass
class SyncResult:
    written: List[str] = field(default_factory=list)
    unchanged: List[str] = field(default_factory=list)
    skipped: List[str] = field(default_factory=list)
    modified: List[str] = field(default_factory=list)  # 手元で変更されているため上書きしなかった
    removed: List[str] = field(default_factory=list)


# ---------------- エンジン由来のファイル ----------------

def engine_files(lang: str) -> Dict[str, bytes]:
    """ワークスペースに書き出すファイル（相対パス → 内容）。"""
    src = assets_dir(lang)
    files = {
        "AGENTS.md": (src / "AGENTS.md").read_bytes(),
        "CLAUDE.md": b"@AGENTS.md\n",
        ".env.example": (ASSETS_DIR / "env.example").read_bytes(),
        WRAPPER_NAME: WRAPPER.encode("utf-8"),
    }
    for skill in sorted((src / "skills").glob("*/SKILL.md")):
        files[f".agent/skills/{skill.parent.name}/SKILL.md"] = skill.read_bytes()
    return files


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:16]


def assets_hash(lang: str) -> str:
    h = hashlib.sha256()
    for rel, content in sorted(engine_files(lang).items()):
        h.update(rel.encode() + b"\0" + content + b"\0")
    return h.hexdigest()[:16]


def _manifest_path(root: Path) -> Path:
    return meta_dir(root) / MANIFEST


def _load_manifest(root: Path) -> Dict:
    try:
        return json.loads(_manifest_path(root).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"files": []}


def locally_modified(root: Path) -> List[str]:
    """`priorwork sync` が書き出したあと、手元で書き換えられたファイル。"""
    recorded = _load_manifest(root).get("hashes", {})
    return [rel for rel, sha in sorted(recorded.items())
            if (root / rel).is_file() and _sha((root / rel).read_bytes()) != sha]


def sync_status(root: Path) -> Optional[str]:
    """AGENTS.md・スキルに問題（古い / 手元で変更）があればメッセージ、なければ None。"""
    notes = []
    if _load_manifest(root).get("hash") != assets_hash(workspace_lang(root)):
        notes.append(t("AGENTS.md and the skills do not match the engine's version. Update them with `./priorwork sync`"))
    modified = locally_modified(root)
    if modified:
        notes.append(t("Some files were changed by hand ({files}); `./priorwork sync` leaves them alone. "
                       "Move your own instructions to AGENTS.local.md and restore them with `./priorwork sync --force`",
                       files=", ".join(modified)))
    return "\n   ".join(notes) or None


def diff(root: Path) -> str:
    """ワークスペースのファイルとエンジンの版との差分（unified diff）。"""
    out = []
    for rel, content in engine_files(workspace_lang(root)).items():
        dest = root / rel
        cur = dest.read_text(encoding="utf-8", errors="replace") if dest.is_file() else ""
        new = content.decode("utf-8")
        if cur != new:
            out.extend(difflib.unified_diff(cur.splitlines(True), new.splitlines(True),
                                            f"workspace/{rel}", f"engine/{rel}"))
    return "".join(out)


def _refuse_engine_repo(root: Path):
    """エンジン自身のリポジトリ（開発用の AGENTS.md などがある）は書き換えない。"""
    if (root / "priorwork").resolve() == ENGINE_DIR:
        raise ScaffoldError(t("This is the engine's own repository. Run it in a workspace directory"))


def sync(root: Path, force: bool = False) -> SyncResult:
    _refuse_engine_repo(root)
    lang = workspace_lang(root)
    files = engine_files(lang)
    manifest = _load_manifest(root)
    managed, recorded = set(manifest.get("files", [])), manifest.get("hashes", {})
    result, kept = SyncResult(), {}
    for rel, content in files.items():
        dest = root / rel
        if dest.is_file() and dest.read_bytes() == content:
            result.unchanged.append(rel)
        elif dest.exists() and rel not in managed and not force:
            result.skipped.append(rel)
            continue
        elif (dest.is_file() and rel in recorded and not force
              and _sha(dest.read_bytes()) != recorded[rel]):
            result.modified.append(rel)
            kept[rel] = recorded[rel]
            continue
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(content)
            result.written.append(rel)
        if rel == WRAPPER_NAME:
            dest.chmod(0o755)
        kept[rel] = _sha(content)

    for rel in sorted(managed - set(files)):  # エンジンから無くなったスキル、旧名の ./lit など
        stale = root / rel
        if stale.is_file():
            stale.unlink()
            result.removed.append(rel)
            for parent in stale.parents:
                if parent == root or any(parent.iterdir()):
                    break
                parent.rmdir()

    if ensure_gitignore(root):
        result.written.append(".gitignore")

    local = root / "AGENTS.local.md"
    if not local.exists():
        local.write_text(LOCAL_INSTRUCTIONS[lang], encoding="utf-8")
        result.written.append("AGENTS.local.md")

    link = root / SKILLS_LINK
    if not link.exists() and not link.is_symlink():
        link.parent.mkdir(parents=True, exist_ok=True)
        try:
            os.symlink("../.agent/skills", link)
            result.written.append(SKILLS_LINK)
        except OSError:  # Windows でシンボリックリンクを作る権限が無いとき
            result.skipped.append(SKILLS_LINK)
    elif not link.is_symlink():
        result.skipped.append(SKILLS_LINK)

    _manifest_path(root).parent.mkdir(parents=True, exist_ok=True)
    manifest = {"engine_version": __version__, "lang": lang,
                "hash": "" if result.skipped or result.modified else assets_hash(lang),
                "files": sorted(kept), "hashes": dict(sorted(kept.items()))}
    _manifest_path(root).write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return result


def _drop_block(lines: List[str], begin: str, end: str) -> List[str]:
    if begin in lines and end in lines:
        i, j = lines.index(begin), lines.index(end)
        if i < j:
            return lines[:i] + lines[j + 1:]
    return lines


def ensure_gitignore(root: Path) -> bool:
    path = root / ".gitignore"
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    for begin, end in ((GITIGNORE_BEGIN, GITIGNORE_END), *LEGACY_GITIGNORE_BLOCKS):
        lines = _drop_block(lines, begin, end)
    lines = [ln for ln in lines if ln.strip() not in LEGACY_GITIGNORE_LINES]
    while lines and not lines[-1].strip():
        lines.pop()
    text = "\n".join(lines + ([""] if lines else []) + [GITIGNORE_BEGIN, *GITIGNORE_LINES, GITIGNORE_END]) + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def in_git_repo(root: Path) -> bool:
    try:
        return subprocess.run(["git", "rev-parse", "--is-inside-work-tree"], cwd=root,
                              capture_output=True, text=True).stdout.strip() == "true"
    except OSError:
        return False


def git_init(root: Path) -> bool:
    """ワークスペースは Git（GitHub）で管理する前提。リポジトリでなければ `git init` する。作ったら True。"""
    if in_git_repo(root) or not shutil.which("git"):
        return False
    subprocess.run(["git", "init", "-q"], cwd=root, check=True)
    return True


def requirement_line(version: str = __version__) -> str:
    return f"{DIST}=={version.lstrip('v')}"


def init(root: Path, force: bool = False, lang: Optional[str] = None) -> SyncResult:
    """ワークスペースを作る。言語は初めて作るときだけ決まる（既にあれば設定を変えない）。"""
    _refuse_engine_repo(root)
    root.mkdir(parents=True, exist_ok=True)
    created_repo = git_init(root)
    for d in (reports_dir(root), state_dir(root), cache_dir(root), data_dir(root)):
        d.mkdir(parents=True, exist_ok=True)
    config = load_config(root)
    if "lang" not in config:
        config["lang"] = i18n.normalize(lang or i18n.language())
        save_config(root, config)
    req = root / "requirements.txt"
    if not req.exists():
        req.write_text(requirement_line() + "\n", encoding="utf-8")
    ensure_gitignore(root)
    result = sync(root, force=force)
    if created_repo:
        result.written.insert(0, ".git/ (git init)")
    return result


# ---------------- エンジンの更新 ----------------

def _version_key(v: str):
    return tuple(int(n) for n in re.findall(r"\d+", v))


def latest_version() -> str:
    """PyPI にある最新の版（X.Y.Z）。"""
    import requests
    try:
        resp = requests.get(PYPI_JSON, timeout=30)
        resp.raise_for_status()
        return resp.json()["info"]["version"]
    except (requests.RequestException, ValueError, KeyError) as e:
        raise ScaffoldError(t("Could not look up the latest version on PyPI: {error}", error=e)) from e


def pin_requirements(root: Path, version: str) -> str:
    """requirements.txt のエンジンの行を、指定の版に固定する（旧名 litsurvey の行も置き換える）。書き換え後の行を返す。"""
    line = requirement_line(version)
    path = root / "requirements.txt"
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    for i, cur in enumerate(lines):
        if re.match(rf"\s*(?:{DIST}|litsurvey)\b", cur):
            lines[i] = line
            break
    else:
        lines.insert(0, line)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return line


def upgrade(root: Path, version: Optional[str] = None) -> str:
    """エンジンを指定（既定は最新）の版に上げ、AGENTS.md・スキルを同期する。上げた版を返す。"""
    _refuse_engine_repo(root)
    version = (version or latest_version()).lstrip("v")
    if not re.fullmatch(r"\d+(\.\d+)*", version):
        raise ScaffoldError(t("Give the version as X.Y.Z: {version}", version=version))
    old = (root / "requirements.txt").read_text(encoding="utf-8") if (root / "requirements.txt").exists() else None
    pin_requirements(root, version)
    try:
        subprocess.run([sys.executable, "-m", "pip", "install", "-r", str(root / "requirements.txt")], check=True)
    except (OSError, subprocess.CalledProcessError) as e:
        if old is None:
            (root / "requirements.txt").unlink()
        else:
            (root / "requirements.txt").write_text(old, encoding="utf-8")
        raise ScaffoldError(t("pip install failed (requirements.txt was restored): {error}", error=e)) from e
    # 更新後のコードで同期する（このプロセスは古いコードを読み込んでいる）。手元の priorwork/ を拾わないよう別のディレクトリから実行する
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run([sys.executable, "-m", "priorwork", "sync"], cwd=tmp, check=True,
                       env={**os.environ, "PRIORWORK_WORKSPACE": str(root)})
    return version


# ---------------- 旧構成からの移行 ----------------

def is_lit_workspace(root: Path) -> bool:
    """旧名 lit のワークスペース（`.lit/` があり、`.priorwork/` がまだ無い）。"""
    return (root / LEGACY_META).is_dir() and not meta_dir(root).is_dir()


def is_old_layout(root: Path) -> bool:
    """さらに古い構成（surveys/ に md と json が同居）のまま、新しい構成にはまだ状態ファイルが無い。"""
    old = root / "surveys"
    return (old.is_dir() and any(old.glob("*.json")) and not any(state_dir(root).glob("*.json"))
            and not any((root / LEGACY_META / "surveys").glob("*.json")))


def is_legacy(root: Path) -> bool:
    return is_lit_workspace(root) or is_old_layout(root)


def leftover_engine_files(root: Path) -> List[Path]:
    """旧テンプレートのコピーに残っている、いまは不要なエンジンのファイル。"""
    if not (root / "litsurvey" / "__init__.py").exists() or not (root / "templates" / "literature_review.md").exists():
        return []
    names = ["litsurvey", "tests", "templates", "pyproject.toml", "litsurvey.egg-info", ".pytest_cache"]
    return [root / n for n in names if (root / n).exists()]


def _move(src: Path, dst: Path, moved: List[str], root: Path):
    if dst.exists():
        raise ScaffoldError(t("The destination already exists: {path}", path=dst.relative_to(root)))
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(src), str(dst))
    moved.append(f"{src.relative_to(root)} → {dst.relative_to(root)}")


def migrate(root: Path, clean: bool = False) -> Dict:
    """旧構成を新しい構成に移す。戻り値: {moved, removed, leftover, skipped, backup, stale_readme, rendered, unreadable}"""
    _refuse_engine_repo(root)
    moved: List[str] = []
    removed: List[str] = []

    # 1. 旧名 lit: .lit/ をまるごと .priorwork/ に（状態・キャッシュ・sync.json）。中身は日本語
    if (root / LEGACY_META).is_dir():
        if meta_dir(root).exists():
            raise ScaffoldError(t("Both {old} and {new} exist. Keep one of them and run it again",
                                  old=f"{LEGACY_META}/", new=f"{meta_dir(root).name}/"))
        _move(root / LEGACY_META, meta_dir(root), moved, root)
        if not config_path(root).exists():
            save_config(root, {"lang": "ja"})
        if (root / "requirements.txt").exists():
            before = (root / "requirements.txt").read_text(encoding="utf-8")
            pin_requirements(root, __version__)
            if (root / "requirements.txt").read_text(encoding="utf-8") != before:
                moved.append(f"requirements.txt → {requirement_line()}")

    # 2. さらに古い構成: 先に移行先の衝突を調べ、途中で止まって半端な状態にならないようにする
    old_surveys, old_data = root / "surveys", root / "data"
    plan = []
    if old_surveys.is_dir():
        plan += [(p, (reports_dir(root) if p.suffix == ".md" else state_dir(root)) / p.name)
                 for p in sorted(old_surveys.iterdir()) if p.suffix in (".md", ".json")]
    for name in ("fulltext", "zotero"):
        if (meta_dir(root) / name).is_dir():
            plan.append((meta_dir(root) / name, cache_dir(root) / name))
    if old_data.is_dir():
        plan += [(p, data_dir(root) / p.name) for p in sorted(old_data.glob("*.csv"))]
    clashes = [dst for _, dst in plan if dst.exists()]
    if clashes:
        raise ScaffoldError(t("The destination already exists: {path}",
                              path=", ".join(str(c.relative_to(root)) for c in clashes)))
    if plan and not config_path(root).exists():
        save_config(root, {"lang": "ja"})

    for src, dst in plan:
        _move(src, dst, moved, root)
    for d in (old_surveys, old_data):
        keep = d / ".gitkeep"
        if keep.exists() and [p for p in d.iterdir() if p != keep] == []:
            keep.unlink()
        if d.is_dir() and not any(d.iterdir()):
            d.rmdir()
            removed.append(f"{d.relative_to(root)}/")

    # 上書きされる旧ファイルは退避しておく
    backup = cache_dir(root) / "migrate-backup"
    lang = workspace_lang(root)
    managed = _load_manifest(root).get("files", [])
    for rel, content in engine_files(lang).items():
        cur = root / rel
        if cur.is_file() and cur.read_bytes() != content and rel not in managed:
            (backup / rel).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(cur, backup / rel)

    result = init(root, force=True)

    # レポートの管理ブロックの印を priorwork: に書き換える（再生成）
    rendered, unreadable = [], []
    for path in sorted(state_dir(root).glob("*.json")):
        try:
            s = Survey.load(path.name, reports_dir(root), state_dir(root))
            if s.render():
                rendered.append(str(s.md_path.relative_to(root)))
            else:
                s.save()   # 状態ファイルの形式だけ新しくする
        except (SurveyError, ValueError, KeyError) as e:
            unreadable.append(f"{path.relative_to(root)}: {e}")

    leftover = leftover_engine_files(root)
    if clean and leftover:
        if any(p.resolve() == ENGINE_DIR for p in leftover):
            raise ScaffoldError(t("The engine running now is inside the workspace, so it cannot be deleted. "
                                  "Run it with the engine installed by pip (.venv/bin/priorwork)"))
        for p in leftover:
            shutil.rmtree(p) if p.is_dir() else p.unlink()
            removed.append(str(p.relative_to(root)) + ("/" if p.is_dir() else ""))
        leftover = []
    readme = root / "README.md"
    stale_readme = readme.is_file() and "対話しながら作る社会科学の文献サーベイ" in readme.read_text(encoding="utf-8")
    return {"stale_readme": stale_readme, "moved": moved, "removed": removed + result.removed,
            "leftover": [str(p.relative_to(root)) for p in leftover], "skipped": result.skipped,
            "backup": [str(backup.relative_to(root))] if backup.exists() else [], "rendered": rendered,
            "unreadable": unreadable}
